PORT = 8220

SMTP_SERVICE_READY = "220"
REQUESTED_ACTION_COMPLETED = "250"
COMMAND_SYNTAX_ERROR = "500"
INCORRECT_AUTH = "535"
ENTER_MESSAGE = "354"
AUTH_INPUT = "334"
AUTH_SUCCESS = "235"
EMAIL_END = "@patriots.in" # Find which combination of chars indicates email end
GOODBYE = "221"
